In [5]:
import cv2
img0 = cv2.imread("gray.png",0)
img0

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
img1 = cv2.imread("gray.png",1)
img1

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [9]:
cv2.imwrite("newGray.png",img1)

True

In [17]:
#slicing
img1[0:2]

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]]], dtype=uint8)

In [13]:
#iterating
for i in img1:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [14]:
for i in img1.flat:
    print(i)

187
187
187
158
158
158
104
104
104
121
121
121
143
143
143
198
198
198
125
125
125
255
255
255
255
255
255
147
147
147
209
209
209
134
134
134
255
255
255
97
97
97
182
182
182


In [24]:
import numpy
img2 = numpy.hstack(img1)
img2

array([187, 187, 187, 198, 198, 198, 209, 209, 209, 158, 158, 158, 125,
       125, 125, 134, 134, 134, 104, 104, 104, 255, 255, 255, 255, 255,
       255, 121, 121, 121, 255, 255, 255,  97,  97,  97, 143, 143, 143,
       147, 147, 147, 182, 182, 182], dtype=uint8)

In [27]:
import numpy
img3 = numpy.vstack(img1)
img3

array([[187],
       [187],
       [187],
       [198],
       [198],
       [198],
       [209],
       [209],
       [209],
       [158],
       [158],
       [158],
       [125],
       [125],
       [125],
       [134],
       [134],
       [134],
       [104],
       [104],
       [104],
       [255],
       [255],
       [255],
       [255],
       [255],
       [255],
       [121],
       [121],
       [121],
       [255],
       [255],
       [255],
       [ 97],
       [ 97],
       [ 97],
       [143],
       [143],
       [143],
       [147],
       [147],
       [147],
       [182],
       [182],
       [182]], dtype=uint8)